#' Generate a pseudo-random conspiracy theory
#'
#' @param agent a list or character vector of potential agents in the form  "x is" or "y are"
#' @param adverb a list or character vector of adverbs for the style of action
#' @param action  a list or character vector of potential actions of the conspirators.
#'
#' @return a character string containing a conspiracy theory
#' 
#' @export
#'
#' @examples
#' conspirator::conspire()
conspire <- function(agent = NULL, adverb = NULL, action = NULL) {

  if (!is.list(agent) && !is.character(agent) && !is.null(agent)) stop("agent is not a list or character vector")
  if (!is.list(adverb) && !is.character(adverb) && !is.null(adverb)) stop("agent is not a list or character vector")
  if (!is.list(action) && !is.character(action) && !is.null(action)) stop("agent is not a list or character vector")
  
  if (is.null(agent)) {  
  agent <-  list("The government is", 
                 "Aliens are", 
                 "Snake people are", 
                 "Very angry quolls are", 
                 "Underappreciated household appliances are",
                 "Big Pharma is",
                 "Big Oil is",
                 "Scientists are", 
                 "Sulphur-crested cockatoos are", 
                 "Cats are", 
                 "Drug barons are",
                 "The population of peoples named Mathew, Matthew, Matvei, Matej, Matko, Matityahu, Mateus, Matteo, etc. are",
                 "The Knights Templar are", 
                 "The less-widely-known Knights Hospitalier are", 
                 "A ritual-soaked conclave of turners and fitters are", 
                 "Androids are",
                 "A collective of empty-nesters are",
                 "Lobbyists are",
                 "Bill Gates is",
                 "The British Royal Family is", 
                 "Social media corporations are", 
                 "Media goliaths are",
                 "Intelligence and Security services are",
                 "The military is",
                 "Space force is",
                 "The mining industry is",
                 "The media is", 
                 "Trash pandas are", 
                 "So called culture warriors are",
                 "The youth are",
                 "Secret societies are",
                 "Rattlers and Eagles are",
                 "Technocrats are",
                 "Bureaucrats are",
                 "Organised criminals are",
                 "A sect within the church is", 
                 "The music industry is",
                 "A collection of mononymous actors and recording artists are",
                 "HR managers are",
                 "Secret societies are",
                 "The Merovingians are",
                 "The Wiggles are",                 
                 "The International Labour Organisation is",
                 "The UN is",                 
                 "The Men in Black are",
                 "The Rosicrucians are",                 
                 "The Priory of Sion is",
                 "Majestic 12 is",                 
                 "Trekkies are",
                 "Followers of Nostradamus are",                 
                 "The Boy Scouts of America are",
                 "The Triads are",                 
                 "The Yakuza are",
                 "The Hermetic Order of the Golden Dawn is",                 
                 "HYDRA is",
                 "The Order of the Dragon is",                 
                 "The World Wildlife Fund is",
                 "The SPCA is",                 
                 "The Automobile Association is",
                 "The Military-Industrial Complex is",                 
                 "The YMCA is",
                 "The Thule society is",
                 "NFT speculators are", 
                 "*nix users are", 
                 "The cult of Apple are",
                 "A collaboration of psychologists across Australia and New Zealand are",
                 "The unicode consortium are"
                 )
  }
  
  if (is.null(adverb)) {
  adverb <-  list("secretly", 
                     "covertly",
                     "maliciously",
                     "surreptitiously",
                     "deviously",
                     "insidiously"             
                    )
  }
  
  if (is.null(action)) {
  action <- list("swapping toothpaste for moisturiser.",
                 "putting up roadwork signs where there is no planned roadwork.",
                 "planning to unify against humanity.",
                 "rearranging your cutlery drawer while you sleep.", 
                 "stealing one sock per load of laundry.",
                 "exploiting us for food and bodyheat.", 
                 "upholding the status quo.",
                 "making git commits with uninformative messages.",
                 "faking moon landings.",
                 "putting microchips that track your location and activities into your mobile phone.",
                 "engaging in insider trading.",
                 "putting chemicals like sodium, chlorine, and even occasionally iodine in salt.",
                 "raising an underground army of mole-people.", 
                 "disseminating rumours about fake conspiracies.", 
                 "placing mysterious monoliths and obelisks around the world.", 
                 "green-lighting terrible Netflix originals.",
                 "cybernetically enhancing the public.", 
                 "making software that devises malevolent schemes.",
                 "financing Sky news.",
                 "giving people more rights, and you see that means that you get less rights... that's how it works you know.",
                 "holding secret accounts in your name that you can gain access to by wrapping your names in arbitrary punctuation.",
                 "replacing the secret herbs and spices one at a time.", 
                 "hiding the existence of a surprisingly large number of animals.",
                 "creating a race of bioengineered super soldiers.",
                 "producing chemtrails containing mind-controlling chemicals.",
                 "brewing low alcohol beer that tastes like real beer.", 
                 "stealing likes from my edgy tweets.",
                 "replacing butter with margarine.", 
                 "concealing the real truth about the Berenstein bears.",
                 "hiding the healing properties of outrage culture.", 
                 "replacing all normal distributions with cauchy distributions.",
                 "encouraging parents to drop over whenever they want.",
                 "disseminating rumours about a flat earth, to distract from the reality that the earth is a hollow sphere.",
                 "disseminating rumours about a hollow earth, to distract from the reality that the earth is flat.",
                 "changing the flavour of tapwater.",
                 "cancelling your favourite TV shows.",
                 "recording inexplicably terrible yet popular covers of classic songs.",
                 "enrolling everyone in mandatory mindfulness seminars.",
                 "scheduling meetings that should have been emails.", 
                 "errecting strange new telecommunication towers.", 
                 "breeding a more persistent, fecund, and louder variety of mosquito.",
                 "signing you up to promotional emails and text messages.",
                 "setting very specific password requirements, but not telling you what they are.", 
                 "promoting the idea that speaking on the telephone is good.", 
                 "making ballpoint pens that appear fine, but then run out halfway through a sentence.", 
                 "delegitimising courts by adding gold-fringes to flags.",
                 "hiding the existence of aliens.",
                 "promoting belief in the existence of aliens.",
                 "putting chemicals in the water supply.",
                 "replacing celebrities with dopplegangers.",
                 "building an elaborate complex under Denver airport.",
                 "running their organisation from the basement of a pizza place.",
                 "hiding messages in books that you can decode with computers.",
                 "faking the deaths of political figures.", 
                 "developing weather controlling technologies.",
                 "building an earthquake machine.",
                 paste0("hiding the fact that the current year is ", as.numeric(format(Sys.Date(), "%Y"))-297, "."), 
                 "suppressing zero-point energy technology.", 
                 "leaving clues to their conspiracy literally everywhere.", 
                 "being simultanously capable of running a grand conspiracy, and being rubbish at opsec.",
                 "making it so everyone will have to live in environmentally sustainable housing.",
                 "censoring powerful people in subtle ways that are hard to actually quantify.",
                 "forcing you to at least consider perspectives other than your own.", 
                 "falsifying the whole history of modern epidemiology.", 
                 "delivering vaccines with time-travelling nanoparticles.", 
                 "funding left-wing radicals somehow.",
                 "faking the deaths of celebrities.", 
                 "working to bring back polio and smallpox.",
                 "building bunkers and arks for the coming apocalypse.", 
                 "investing in fossil fuels.",
                 "boycotting fairtrade products.",
                 "getting everyone hooked on painkillers.", 
                 "patching over structural problems with medication.",
                 "making flimsier shoelaces.",
                 "supressing research into pockets in women's clothing.",
                 "literally turning people into Sheep (Ovis aries).",
                 "moving things that you momentarily put down.", 
                 "creating junk mail.",
                 "sending you phishing tests.",
                 "slowing your wifi at critical moments.",
                 "causing buffering in your streaming videos just before a big reveal.",
                 "parking on the line between two parking spaces.",
                 "leaving dog poo everywhere.",
                 "stealing random packages from the mail.",
                 "placing chewing gum under tables and chairs.",
                 "forcing computer updates at inconvenient times.",
                 "tangling headphone cables.",
                 "messing with that notification that the other person is typing in your messaging services.",
                 "creating spammy casual games.",
                 "promoting the pay-to-win video game model.", 
                 "inventing preposterous neologisms like \"negative profitability\".",
                 "a distraction from the real problems in society.",
                 "hoarding wealth.",
                 "suppressing the public through exploitation of \"surplus value\".",
                 "making specious arguments about the boundaries of prejudice and discrimination.",
                 "hiding wage theft.",
                 "alienating the public from their shared humanity.",
                 "reducing the complexity of the world into binary choices.",
                 "encouraging clicktivism as a replacement for direct action.",
                 "making collectible junk that children oddly like.",
                 "moving furniture just enough to make you stub your toe.", 
                 "sowing confusion about the ideas of \"cancellation\" and \"consequences\".",
                 "encouraging the use of Employee Assistance Programs.", 
                 "suppressing voting rights.", 
                 "discouraging people from talking about how much they get paid.",
                 "busting unions.", 
                 "replacing your light bulbs with energy efficient ones.",
                 "suppressing longer lasting light bulbs.",
                 "making it so you have to flush toilets 10... 15 times.",
                 "forcing you to collect your package from a depot 2+ hours away.", 
                 "making symbolic gestures rather than doing anything to fix the world.", 
                 "complaining about taboo words that perpetuate inequality.",
                 "making words taboo so people can't talk about inequality.",
                 "waging the culture wars.",
                 "running a recruitment program embedded in clues and coded messages throughout the internet.",
                 "removing the setting that gets your toast right on the first try.",
                 "making smoke alarms really sensitive to burnt toast.",
                 "swamping rating systsems with inane one-star reviews.",
                 "swamping rating systsems with irrelevant five-star reviews.",
                 "searching for the Ark of the Covenant.",
                 "hiding members of the Merovingian dynasty.",
                 "searching for the lost city of Atlantis.",
                 "sending messages to each other encoded in oil paintings.",
                 "communicating secret messages in engravings printed on banknotes.",
                 "producing reality TV shows.", 
                 "introducing your parents to things that you like.",
                 "engineering cup-holders that are just the wrong size.",
                 "designing take-away coffee lids that don't seal properly.",
                 "awakening the Great Cthulhu.",
                 "using Tik Tok to turn pre-millennials against us.",
                 "creating even more PowerPoint templates.",
                 "reactivating the Philadelphia experiment.",
                 "excavating the pyramids of Giza.",
                 "translating the lines of Nazca.",
                 "tapping into the Earth's telluric currents.",
                 "unlocking the secret of avocados.",
                 "squaring the circle.",
                 "solving the three body problem using numerology.",
                 "translating the Voynich manuscript.",
                 "searching for the Holy Grail.",
                 "communicating with extradimensional beings.",
                 "holding Elvis prisoner.",
                 "operating a weather control satellite network.",
                 "defrosting a gigantic frozen alien in Antarctica.",
                 "inserting subliminal messages into breakfast cereal advertisements.",
                 "planting tracking devices in people's fillings.",
                 "constructing a giant spaceship to save the world's wealthy in the event of environmental apocalypse.", 
                 "uplifting apes to human levels of intelligence.", 
                 "making line dancing popular again.",
                 "summoning demons to do their bidding.", 
                 "building a secret military moon base.", 
                 "destroying the minds of scientists using infuriating journal submission portals.",
                 "enumerating the nine billion names of God.",
                 "harnessing the power of vril.",
                 "creating the philosopher's stone.",
                 "starting fires using satellite-mounted lasers.",
                 "channeling the power of the æther.",
                 "mass-producing phlostigon.",
                 "searching for the lost continent of Lemuria.",
                 "concealing relics of ancient Hyperborea.",
                 "pillaging El Dorado.",
                 "seeking the spiritual powers of Shambhala.", 
                 "reconstructing the tower of Babel.",
                 "searching for the fountain of youth.",
                 "devising a weapon to destroy Yggdrasil.", 
                 "adding spelling errors to restaurant menus.",
                 "messing with your autocorrect settings.", 
                 "reanimating the terracotta armies of  Qin Shi Huang.",
                 "hiding the existence of the planet Nibiru.", 
                 "cloning whoever... or whatever... is pictured in the shroud of Turin.", 
                 "reading aloud from the Necronomicon.",
                 "exploring the structures beneath stonehenge.",
                 "doing research on what lays beneath in Centralia, Pennsylvania.",
                 "launching an expedition into the Dyatalov pass.",
                 "making sacrifices to the Darvaza gas crater.",
                 "hiding the truth about the Bermuda triangle.", 
                 "activating the Moai of Easter Island.",
                 "shortening phone battery life.",
                 "creating phone reception black spots.",
                 "making new cryptocurrencies.", 
                 "promoting conflict between programming languages.", 
                 "eliminating compatability with S.",
                 "planting Agapanthus.",
                 "seeing you while you're sleeping and knowing when you're awake.",
                 "introducing poll taxes.",
                 "boosting the profile of narcisistic villains.",
                 "making you self-conscious about the shape of your nose.",
                 "adjusting the climate control settings.", 
                 "distracting from the real threats posed by cassowaries and sinkholes."
                 )
  }
  
  cat(paste(sample(agent, 1), 
        sample(adverb, 1),
        sample(action, 1)
        ))
}
