#' Generate a pseudo-random conspiracy theory
#'
#' @return a character string containing a conspiracy theory
#' 
#' @export
#'
#' @examples
#' conspirator::conspire()
conspire <- function() {
  
  agent <-  list("The government is", 
                 "Aliens are", 
                 "Snake people are", 
                 "Very angry quolls are", 
                 "Underappreciated household appliances are",
                 "Big Pharma is", 
                 "Scientists are", 
                 "Sulphur-crested cockatoos are", 
                 "Cats are", 
                 "Drug barons are",
                 "The population of peoples named Mathew, Matthew, Matvei, Matej, Matko, Matityahu, Mateus, Matteo, etc. are",
                 "The Knights Templar are", 
                 "The less-widely-known Knights Hospitalier are", 
                 "A ritual-soaked conclave of turners and fitters are", 
                 "Androids are",
                 "A collective of empty-nesters are",
                 "Lobbyists are",
                 "Bill Gates is",
                 "The British Royal Family is", 
                 "Social media corporations are", 
                 "Media goliaths are",
                 "Intelligence and Security services are",
                 "The military is",
                 "Space force is",
                 "The mining industry is",
                 "The media is", 
                 "Trash pandas are", 
                 "So called culture warriors are",
                 "The youth are",
                 "Secret societies are",
                 "Rattlers and Eagles are",
                 "Technocrats are",
                 "Bureaucrats are",
                 "Organised criminals are",
                 "A sect within the church is", 
                 "The music industry is"
                 )
  
  adjective <-  list("secretly", 
                     "covertly",
                     "maliciously",
                     "surreptitiously",
                    "deviously"
                    )
  
  action <- list("swapping toothpaste for moisturiser.",
                 "putting up roadwork signs where there is no planned roadwork.",
                 "planning to unify against humanity.",
                 "rearranging your cutlery drawer while you sleep.", 
                 "stealing one sock per load of laundry.",
                 "exploiting us for food and bodyheat.", 
                 "upholding the status quo... That's it.",
                 "making git commits with uninformative messages.",
                 "faking moon landings.",
                 "putting microchips that track your location and activities into your mobile phone.",
                 "engaging in insider trading.",
                 "putting chemicals like sodium, chlorine, and even occasionally iodine in salt.",
                 "raising an underground army of mole-people.", 
                 "disseminating rumours about fake conspiracies.", 
                 "placing mysterious monoliths and obelisks around the world.", 
                 "green-lighting terrible Netflix originals.",
                 "cybernetically enhancing the public.", 
                 "making software that devises malevolent schemes.",
                 "financing Sky news.",
                 "giving people more rights, and you see that means that you get less rights... that's how it works you know.",
                 "holding secret accounts in your name that you can gain access to by wrapping your names in arbitrary punctuation.",
                 "replacing the secret herbs and spices one at a time.", 
                 "hiding the existence of a surprisingly large number of animals.",
                 "creating a race of bioengineered super soldiers.",
                 "producing chemtrails containing mind-controlling chemicals.",
                 "brewing low alcohol beer that tastes like real beer.", 
                 "stealing likes from my edgy tweets.",
                 "replacing butter with margarine.", 
                 "concealing the real truth about the Berenstein bears.",
                 "hiding the healing properties of outrage culture.", 
                 "replacing all normal distributions with cauchy distributions.",
                 "encouraging parents to drop over whenever they want.",
                 "disseminating rumours about a flat earth, to distract from the reality that the earth is a hollow sphere.",
                 "disseminating rumours about a hollow earth, to distract from the reality that the earth is flat.",
                 "changing the flavour of tapwater.",
                 "cancelling your favourite TV shows.",
                 "recording inexplicably terrible yet popular covers of classic songs.",
                 "enrolling everyone in mandatory mindfulness seminars.",
                 "scheduling meetings that should have been emails.", 
                 "errecting strange new telecommunication towers.", 
                 "breeding a more persistent, fecund, and louder variety of mosquito.",
                 "signing you up to promotional emails and text messages.",
                 "setting very specific password requirements, but not telling you what they are.", 
                 "promoting the idea that speaking on the telephone is good.", 
                 "making ballpoint pens that appear fine, but then run out halfway through a sentence.", 
                 "delegitimising courts by adding gold-fringes to flags.",
                 "hiding the existence of aliens.",
                 "promoting belief in the existence of aliens.",
                 "putting chemicals in the water supply.",
                 "replacing celebrities with dopplegangers.",
                 "building an elaborate complex under Denver airport.",
                 "running their organisation from the basement of a pizza place.",
                 "hiding messages in books that you can decode with computers.",
                 "faking the deaths of political figures.", 
                 "developing weather controlling technologies.",
                 "building an earthquake machine.",
                 paste0("hiding the fact that the current year is ", as.numeric(format(Sys.Date(), "%Y"))-297, "."), 
                 "suppressing zero-point energy technology.", 
                 "leaving clues to their conspiracy literally everywhere.", 
                 "being simultanously capable of running a grand conspiracy, and being rubbish at opsec.",
                 "making it so everyone will have to live in environmentally sustainable housing.",
                 "censoring powerful people in subtle ways that are hard to actually quantify.",
                 "forcing you to at least consider perspectives other than your own.", 
                 "falsifying the whole history of modern epidemiology."
                 )
  
  paste(sample(agent, 1), 
        sample(adjective, 1),
        sample(action, 1)
        )
}
